---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus-crd-source
  namespace: flux-system
spec:
  # renovate: datasource=github-releases
  url: https://github.com/prometheus-operator/prometheus-operator.git
  ref:
    tag: v0.56.0
  ignore: |
    # exclude all
    /*
    # include crds
    !/example/prometheus-operator-crd/*
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: prometheus-crd-source
  wait: true
