apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: observability
spec:
  # renovate: registryUrl=https://helm.elastic.co chart=elasticsearch
  version: 8.2.0
  count: 1
  config:
    name: elastic-apm
    apm-server.jaeger.grpc.enabled: true
    apm-server.jaeger.grpc.host: "0.0.0.0:14250"
  http:
    service:
      metadata:
        name: apm
        annotations:
          external-dns.alpha.kubernetes.io/hostname: apm.${SECRET_DOMAIN}
          external-dns.alpha.kubernetes.io/ttl: "120" #optional
      spec:
        type: LoadBalancer
        externalName: apm.${SECRET_DOMAIN}
        ports:
          - name: http
            port: 8200
            targetPort: 8200
          - name: grpc
            port: 14250
            targetPort: 14250
  elasticsearchRef:
    name: apm
    namespace: observability
