# For production, this will require SSO authentication.
# Please refer to the following documentation
# https://github.com/elastic/cloud-on-k8s/blob/master/docs/orchestrating-elastic-stack-applications/security/saml-authentication.asciidoc

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: observability
spec:
  # renovate: registryUrl=https://helm.elastic.co chart=elasticsearch
  version: 8.2.0
  transport:
    service:
      metadata:
        name: elasticsearch
        annotations:
          external-dns.alpha.kubernetes.io/hostname: elasticsearch.${SECRET_DOMAIN}
          external-dns.alpha.kubernetes.io/ttl: "120" #optional
      spec:
        type: LoadBalancer
        externalName: elasticsearch.${SECRET_DOMAIN}
        ports:
          - name: http
            port: 9200
            targetPort: 9200
            protocol: TCP
  nodeSets:
    - name: master
      count: 2
      config:
        node.roles: ["master"]
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 16Gi
            storageClassName: longhorn-static
    - name: data
      count: 3
      config:
        node.roles: ["data"]
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Gi
            storageClassName: longhorn-static
    - name: ingest
      count: 2
      config:
        node.roles: ["ingest"]
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 16Gi
            storageClassName: longhorn-static
    - name: transform
      count: 2
      config:
        node.roles: ["transform"]
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 16Gi
            storageClassName: longhorn-static
    - name: learner
      count: 1
      config:
        node.roles: ["ml"]
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 16Gi
            storageClassName: longhorn-static
