apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
  namespace: observability
spec:
  # renovate: registryUrl=https://helm.elastic.co chart=elasticsearch
  version: 8.2.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: observability
