apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
  namespace: observability
spec:
  version: 8.1.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: observability
