---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - descheduler
  - intel-gpu-plugin
  - metrics-server
  - kube-state-metrics
  - node-exporter
  - nfs-subdir-external-provisioner
  - node-feature-discovery
  - reflector
  - reloader
