# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3LN7nN17/TOncHnFhQc=,iv:Laz99MIaGg+Tsy8CEkOtxUcwvgplWb+g+G6mFL1afuw=,tag:A7bX2JxdWn08dXE9nV5MEw==,type:str]
  SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:EuVcYNeo1sW5PPtR8ZU6I3z3,iv:bip71niqSRW1NDmYnFSXSjl70iPgmaBPu3sbDag1ZtE=,tag:NEpFsPGMHcIBdEAKkw374Q==,type:str]
  SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:sNRLW/DUMLFMcjp4oAs=,iv:Zao8zjR+5qG43Dh6KlWdd+QY0X4YJIhwUFrmUpl8bzI=,tag:JMsWin1mi56C6PhDQRbfYQ==,type:str]
  SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:kPDKCdYjyD7U6JK+Zig=,iv:FmysTwdyQHCHJZ6csCR1QfucZOY6Htebd6dX3cz2IQ0=,tag:yL+0R3O9b6KquZTYqywiDg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16e0y38d5j6lmv96cw3uu9glatusl8stfmksg6f2s0gps95rr5qkq4q75fr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK0krcmJ4YU1NS1VTZGZn
        Rm1weVNMWnR0M2NHNDVUTnZHYjk1WER0ZmdVCm9wdkJxSE5iWkF2UVV2bnpNcUVh
        Q0RLUXQ3cFc3WUZCR2lQVFVDbVhvM1UKLS0tIHZKL3RqTTNaK25CaGt4dVExMzFi
        TjltNVY0dnRrb3ZvLzVBc1N6QTJ4REUKA3WkDtTtM36qXkrZ1UBsqhpRl6Lyuv/P
        AHmzNdff4C9BptdkTz8HwZvXUTg0roIWoWroGk91HCboDbFhyr/CJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-03-21T18:51:26Z"
  mac: ENC[AES256_GCM,data:yXDTCneu6AZpv9bj+c8p5QwNFtIumLO7ZipyyGPA3U4VW9PtX3TuApWL14cUQPM2h1WUipExGMJZ0T8du/dMxd28GcBNGVKH6bqV0KaP1JXlSPhNUpfVAk7qtWc5dQALspbxo9Gjtjro87pb9LukflNYTWpCHvNj2fH+ZY+gNJI=,iv:bSdiRS5oCbwwggvsDxfidDEdHgMWg+qfUULqv5kin2Y=,tag:QHz094Fzz5qsTjtLg+Ko9Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.2
