---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
---
# Remove k3s-managed coredns
$patch: delete
apiVersion: k3s.cattle.io/v1
kind: Addon
metadata:
  name: coredns
  namespace: kube-system
