---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.43.53.1
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: metrics
      port: 9153
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns-tcp
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: kube-dns
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.8.253
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns-udp
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: kube-dns
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 10.0.8.253
  externalTrafficPolicy: Local
