---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: elastic-crd-source
  namespace: flux-system
spec:
  # renovate: datasource=github-releases
  url: https://github.com/elastic/cloud-on-k8s.git
  ref:
    tag: v0.56.0
  ignore: |
    # exclude all
    /*
    # include crds
    !/deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elastic-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: elastic-crd-source
  wait: true
